# Generated by Django 2.2.12 on 2021-11-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Md5str',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('md5str', models.CharField(max_length=25, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
